version: '3'

services:
  database:
    image: postgres
    restart: always
    container_name: "postgres-currencies"
    environment:
      - POSTGRES_DB=currencies
      - POSTGRES_USER=currencies
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'
