version: '3'

services:
  database:
    image: postgres
    restart: always
    container_name: "postgres-currencies"
    environment:
      - POSTGRES_DB=currencies
      - POSTGRES_USER=currencies
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'

  app:
    build: ./app
    restart: always
    container_name: 'app-currencies'
    ports:
      - '8000:8000'
    depends_on:
      - database
    network_mode: 'host'
